// <auto-generated />
using System;
using FinanceDev.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceDev.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251007023853_AlterTableDI1CurvaCorrecaoForeignkey")]
    partial class AlterTableDI1CurvaCorrecaoForeignkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FinanceDev.Domain.Entities.DI1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DI1");
                });

            modelBuilder.Entity("FinanceDev.Domain.Entities.DI1Curva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ajuste")
                        .HasColumnType("REAL");

                    b.Property<int>("IdReferenciaCurva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vencimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdReferenciaCurva");

                    b.ToTable("DI1Curva");
                });

            modelBuilder.Entity("FinanceDev.Domain.Entities.MesVencimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MesVencimento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "F",
                            Mes = "Janeiro"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "G",
                            Mes = "Fevereiro"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "H",
                            Mes = "Março"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "J",
                            Mes = "Abril"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "K",
                            Mes = "Maio"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "M",
                            Mes = "Junho"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "N",
                            Mes = "Julho"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "Q",
                            Mes = "Agosto"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "U",
                            Mes = "Setembro"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "V",
                            Mes = "Outubro"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "X",
                            Mes = "Novembro"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "Z",
                            Mes = "Dezembro"
                        });
                });

            modelBuilder.Entity("FinanceDev.Domain.Entities.ReferenciaCurva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReferenciaCurva");
                });

            modelBuilder.Entity("FinanceDev.Domain.Entities.DI1Curva", b =>
                {
                    b.HasOne("FinanceDev.Domain.Entities.ReferenciaCurva", "ReferenciaCurva")
                        .WithMany()
                        .HasForeignKey("IdReferenciaCurva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenciaCurva");
                });
#pragma warning restore 612, 618
        }
    }
}
