// <auto-generated />
using FinanceDev.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceDev.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004033314_InsertDadosMesVencimento")]
    partial class InsertDadosMesVencimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FinanceDev.Domain.DI1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataReferencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DI1");
                });

            modelBuilder.Entity("FinanceDev.Domain.MesVencimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MesVencimento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "F",
                            Mes = "Janeiro"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "G",
                            Mes = "Fevereiro"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "H",
                            Mes = "Março"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "J",
                            Mes = "Abril"
                        },
                        new
                        {
                            Id = 5,
                            Codigo = "K",
                            Mes = "Maio"
                        },
                        new
                        {
                            Id = 6,
                            Codigo = "M",
                            Mes = "Junho"
                        },
                        new
                        {
                            Id = 7,
                            Codigo = "N",
                            Mes = "Julho"
                        },
                        new
                        {
                            Id = 8,
                            Codigo = "Q",
                            Mes = "Agosto"
                        },
                        new
                        {
                            Id = 9,
                            Codigo = "U",
                            Mes = "Setembro"
                        },
                        new
                        {
                            Id = 10,
                            Codigo = "V",
                            Mes = "Outubro"
                        },
                        new
                        {
                            Id = 11,
                            Codigo = "X",
                            Mes = "Novembro"
                        },
                        new
                        {
                            Id = 12,
                            Codigo = "Z",
                            Mes = "Dezembro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
